name: 'build'
on: 
  push:
    branches:
      - develop
      - "releases/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: add badges
        uses: ./
        with: 
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          badges: 'license,version,github_stars'
          badge-style: 'flat-square'
